package main

import (
	"bytes"
	"exec"
	"flag"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"os"
	"runtime"
)

var (
	pkg  = flag.String("pkg", "watermark", "The package for the generated source file")
	out  = flag.String("out", "-", "The Go source file to store the watermark")
	proj = flag.String("project", "", "The name of the project (prefix to REPO_VERSION)")
)

func main() {
	flag.Parse()

	var fout io.Writer = os.Stdout
	if *out != "-" {
		fout = bytes.NewBuffer(nil)
	}

	host, err := os.Hostname()
	if err != nil {
		log.Fatalf("Could not get hostname: %s", err)
	}

	goVersion := runtime.Version()

	raw, err := exec.Command("git", "describe", "--tags").Output()
	if err != nil {
		log.Fatalf("describe: %s", err)
	}
	tag := string(raw)
	if project := *proj; len(project) > 0 {
		tag = project + "-" + tag
	}

	fmt.Fprintf(fout, "// Autogenerated by watermark\npackage %s\n\n", *pkg)
	fmt.Fprintf(fout, "const (\n")
	fmt.Fprintf(fout, "\tGO_VERSION = %q\n", goVersion)
	fmt.Fprintf(fout, "\tREPO_VERSION = %q\n", tag)
	fmt.Fprintf(fout, "\tCOMPILE_HOST = %q\n", host)
	fmt.Fprintf(fout, ")\n")

	if buf, ok := fout.(*bytes.Buffer); ok {
		err := ioutil.WriteFile(*out, buf.Bytes(), 0666)
		if err != nil {
			log.Fatalf("WriteFile(%q): %s", *out, err)
		}
	}
}
