include $(GOROOT)/src/Make.inc

TARG=kevlar/ircd/core
GOFILES=\
	core.go\
	hooks.go\
	ircd.go\
	server.go\
	config.go\
	registration.go\
	general.go\
	channel.go\
	messaging.go\
	watermark.go\

CLEANFILES += watermark.go

include $(GOROOT)/src/Make.pkg

